pool: fix endpoint related data race.
decred/dcrpool pull request #271
Opened 2020-10-25 16:33 UTC by dnldd

2020-10-25 16:37 UTC, dnldd commented
Fixes

```sh
==================
WARNING: DATA RACE
Read at 0x00c000402fb8 by goroutine 80:
  internal/race.Read()
      /opt/hostedtoolcache/go/1.15.3/x64/src/internal/race/race.go:37 +0x206
  sync.(*WaitGroup).Add()
      /opt/hostedtoolcache/go/1.15.3/x64/src/sync/waitgroup.go:71 +0x219
  github.com/decred/dcrpool/pool.(*Client).run()
      /home/runner/work/dcrpool/dcrpool/pool/client.go:1015 +0x84

Previous write at 0x00c000402fb8 by goroutine 57:
  internal/race.Write()
      /opt/hostedtoolcache/go/1.15.3/x64/src/internal/race/race.go:41 +0x125
  sync.(*WaitGroup).Wait()
      /opt/hostedtoolcache/go/1.15.3/x64/src/sync/waitgroup.go:128 +0x126
  github.com/decred/dcrpool/pool.(*Endpoint).run()
      /home/runner/work/dcrpool/dcrpool/pool/endpoint.go:208 +0xb6

Goroutine 80 (running) created at:
  github.com/decred/dcrpool/pool.(*Endpoint).connect()
      /home/runner/work/dcrpool/dcrpool/pool/endpoint.go:190 +0x1170

Goroutine 57 (running) created at:
  github.com/decred/dcrpool/pool.testEndpoint()
      /home/runner/work/dcrpool/dcrpool/pool/endpoint_test.go:86 +0xa37
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.3/x64/src/testing/testing.go:1123 +0x202
==================
```

2020-10-26 16:27 UTC, jholdstock requested changes

2020-10-26 16:27 UTC, jholdstock commented on pool/endpoint.go
> +// discconnect relays client disconnections to the endpoint for processing.
```suggestion
// disconnect relays client disconnections to the endpoint for processing.
```

2020-10-26 16:40 UTC, jholdstock approved these changes

2020-10-26 16:41 UTC, merged