multi: single miner endpoint.
decred/dcrpool pull request #274
Opened 2020-10-27 20:31 UTC by dnldd

2020-11-27 19:41 UTC, dnldd commented
Tested miner monitoring and upgrade logic with a `DR5` on `mainnet`. Initially recognized as a `DR3` and later upgrading to a `DR5` per the upgrade path.

```sh
2020-11-27 19:26:11.637 [INF] POOL: listening on :5550
2020-11-27 19:29:25.140 [DBG] POOL: Mining client connected. extranonce1=ca750c60, addr=166.170.24.8:35258
2020-11-27 19:29:32.007 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:33.659 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:40.999 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:46.569 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:48.109 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:52.109 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:29:56.349 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:06.370 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:09.189 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:15.849 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:22.246 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:25.340 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:38.170 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:46.229 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:30:50.579 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:31:01.999 [ERR] POOL: submitted work from ca750c60/antminerdr3 is not less than the network target difficulty
2020-11-27 19:31:25.143 [INF] POOL: upgrading ca750c60/antminerdr3 to ca750c60/antminerdr5
2020-11-27 19:31:25.143 [INF] POOL: updated difficulty (228174.031) for ca750c60/antminerdr5 sent
2020-11-27 19:33:06.719 [ERR] POOL: submitted work from ca750c60/antminerdr5 is not less than the network target difficulty
2020-11-27 19:34:43.039 [ERR] POOL: submitted work from ca750c60/antminerdr5 is not less than the network target difficulty
2020-11-27 19:35:13.256 [ERR] POOL: submitted work from ca750c60/antminerdr5 is not less than the network target difficulty
2020-11-27 19:35:38.966 [ERR] POOL: submitted work from ca750c60/antminerdr5 is not less than the network target difficulty
2020-11-27 19:35:46.516 [ERR] POOL: submitted work from ca750c60/antminerdr5 is not less than the network target difficulty
```

2020-12-02 15:09 UTC, jholdstock requested changes

2020-12-02 15:09 UTC, jholdstock commented on pool/endpoint.go
> +var (
I think all of the miner ID related stuff is good candidate for a new file - potentially `miner_id.go`? Miner ID is a distinct concept to the endpoint concept, so arguably does not belong in `endpoint.go`.

- The ID strings
- `minerIDPair`
- `newMinerIDPair`
- `generateMinerIDs`
- `identifyMiner`

2020-12-02 15:09 UTC, jholdstock commented on pool/endpoint.go
> +	// possible upgrades if needed
```suggestion
	// possible upgrades if needed.
```

2020-12-02 15:09 UTC, jholdstock commented on pool/hub.go
> +	// possible upgrades if needed
```suggestion
	// possible upgrades if needed.
```

2020-12-06 20:27 UTC, dnldd commented on gui/assets/templates/index.html
> +                            <p>To connect, set the pool URL to <span class="config">'localhost'</span>, and the miner
Sure thing, let's do that.

2020-12-06 20:28 UTC, dnldd commented on gui/assets/templates/index.html
> +                            <p>For Innosilicon D9 the pool only supports <a
Yes, will update the listing the upcoming commit.

2020-12-06 21:00 UTC, dnldd commented on pool/client.go
> +				continue
Good catch, will call `FetchMinerDifficulty` to ensure it doesn't error before setting `c.miner` and `c.id`.

2020-12-06 21:11 UTC, dnldd commented on pool/client.go
> +		c.mtx.Unlock()
same here, will call `FetchMinerDifficulty` to ensure it doesn't error before setting `c.miner` and `c.id`.

2020-12-06 21:22 UTC, dnldd commented on pool/client.go
> +			c.updateWork()
Agreed, makes sense to reset tries after an upgrade but subs doesn't need a reset, it's always the difference of the current sub count and the previous count therefore will always be greater than or equal to zero and reflect the number of subs within the period being measured.

2020-12-10 08:31 UTC, jholdstock commented on gui/assets/templates/index.html
> +                            <p>To connect, set the pool URL to <span class="config">'localhost'</span>, and the miner
#292

2020-12-10 09:14 UTC, jholdstock approved these changes
Looking good to me! Thanks for taking the time to split up the tests, they will definitely be more manageable going forward.

2020-12-10 10:36 UTC, merged