multi: fix lint issues.
decred/dcrpool pull request #287
Opened 2020-11-13 18:00 UTC by dnldd

This fixes lint outstanding lint issues and wraps errors created by the postgres db driver in order to leverage errors.Is/As functionality.

2020-11-13 18:15 UTC, dajohi approved these changes

2020-11-14 09:43 UTC, jholdstock requested changes

2020-11-14 09:43 UTC, jholdstock commented on errors/error.go
> +	CreateTable = ErrorKind("CreateTable")
CreateTable is specific to SQL and does not apply to Bolt. As we are aiming to make our DB interface agnostic of the implementation, the interface should not include implementation specific errors. 

This also applies to some existing errors - eg. `ErrBucketCreate`  does not apply to SQL, only Bolt.

We should combine these into something more generic, perhaps something like `ErrCreateStorage`

2020-11-14 09:43 UTC, jholdstock commented on errors/error.go
> +	BeginTx = ErrorKind("BeginTx")
All of these tx errors can probably just be `ErrPersistEntry`. Right now, the calling doesn't need to know the precise nature of the failure, its enough just to know that something went wrong. The nested error generated by the SQL library will contain more details for the log file.

2020-11-15 09:31 UTC, jholdstock requested changes

2020-11-15 09:31 UTC, jholdstock commented on errors/error.go
> +	BucketNotFound = ErrorKind("BucketNotFound")
Maybe rename to `StorageNotFound`?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +	makeErr := func(funcName string, table string, err error) error {
passing `funcName` as a param is unnecessary - it is already in scope for the body of this func.

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		return nil, errs.DBError(errs.PersistEntry, desc)
We're fetching here, not persisting

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		rErr := tx.Rollback()
Nice catch finding this, I didnt notice that `Rollback` could return an error.

I'm not sure about the way it is handled though. If we have a `tx.Exec` error and a `tx.Rollback` error, only the `Rollback` error is being returned and logged. The `Exec` error, which could be the root cause of the issue, will be lost. I think we need to log both.

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +			funcName, err.Error())
Why use `"%s", err.Error()` here and in the following instance, when `"%v", err` is used everywhere else?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		desc := fmt.Sprintf("%s: unable to delete account: %v", funcName, err)
include account id?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		return errs.DBError(errs.FetchEntry, desc)
Deleting here, not fetching

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		desc := fmt.Sprintf("%s: unable to delete payment: %v", funcName, err)
include id?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +			desc := fmt.Sprintf("%s: unable to rollback delete payment tx: %v",
As above, we may lose the root cause error here

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		desc := fmt.Sprintf("%s: unable to fetch accepted work: %v",
id?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		desc := fmt.Sprintf("%s: unable to delete account work: %v",
id?

2020-11-15 09:31 UTC, jholdstock commented on pool/postgres.go
> +		desc := fmt.Sprintf("%s: unable to delete job entry: %v",
id?

2020-11-16 13:56 UTC, jholdstock requested changes
Two more things and this is good to go.

2020-11-16 13:56 UTC, jholdstock commented on pool/postgres.go
> +			"time: %s", funcName, err.Error())
`"%v", err`

2020-11-16 13:56 UTC, jholdstock commented on pool/postgres.go
> +			desc := fmt.Sprintf("%s: unable to rollback archived payment "+
Missing initial error

2020-11-17 10:19 UTC, jholdstock approved these changes

2020-11-17 11:53 UTC, merged