Support reverse proxy deployments
decred/dcrpool pull request #301
Opened 2021-01-27 11:47 UTC by jholdstock

This PR is to enable dcrpool deployments behind a dedicated webserver acting as a reverse proxy. 

Changes:
- Listen for GUI connections on plain HTTP (previously hard-coded to HTTPS)
- Make listening IPs for GUI and miner connections configurable (previously hard-coded to 0.0.0.0)

Marking as a draft for now - I will mark for review once I have completed a test deployment behind an nginx instance.

2021-01-27 15:55 UTC, jholdstock commented
Deployed behind nginx at https://pool.jholdstock.uk

2021-01-28 14:31 UTC, dnldd reviewed
Looks good but missing a couple configuration checks.

2021-01-28 14:31 UTC, dnldd commented on config.go
> +		GUIListen:             defaultGUIListen,
`GUIListen` will need to be validated as a tcp address.

2021-01-28 14:31 UTC, dnldd commented on config.go
> +		MinerListen:           defaultMinerListen,
Same for `MinerListen`. Refer to the validation done for `Profile`.

2021-02-06 16:12 UTC, dnldd requested changes

2021-02-06 16:12 UTC, dnldd commented on config.go
> +	defaultGuiTLSKeyFilename     = "dcrpool.key"
We already have instances in the codebase where `GUI` is capitalized so update these for consistency.

2021-02-06 16:12 UTC, dnldd commented on gui/index.go
> +		log.Errorf("Failed to parse port from miner listening address %q",
Error message is capitalized. Any reason why the error itself is not included in the output?

2021-02-08 11:38 UTC, dnldd approved these changes

2021-02-10 09:35 UTC, merged